# Generated by Django 6.0.6 on 2026-07-04 07:53

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "min_length": "Username must be at least 4 characters long.",
                            "unique": "A user with same username already exists.",
                        },
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            users.validators.validate_username,
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell the world about your stack.",
                        null=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=users.models.rename_avatar,
                        validators=[
                            users.validators.validate_file_size,
                            users.validators.validate_image_extension,
                        ],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="Link to your github profile", null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="Link to your linkedin profile", null=True
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to your X (formerly twitter) profile",
                        null=True,
                    ),
                ),
                (
                    "stackoverflow_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to your StackOverflow profile",
                        null=True,
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True, help_text="Your Portfolio website link", null=True
                    ),
                ),
                (
                    "fiver_url",
                    models.URLField(
                        blank=True, help_text="Your Fiver profile link", null=True
                    ),
                ),
                (
                    "upwork_url",
                    models.URLField(
                        blank=True, help_text="Your Upwork profile link", null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("dev", "Developer"),
                            ("client", "Client / Hirer"),
                            ("org", "Organization"),
                        ],
                        default="dev",
                        max_length=10,
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Python, Java, CI/CD, Unity... (Comma separated)",
                        max_length=255,
                    ),
                ),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Pro subscription ends",
                        null=True,
                    ),
                ),
                (
                    "profile_boosts",
                    models.IntegerField(
                        default=0, help_text="Number of profile boosts purchased"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently working here",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "live_url",
                    models.URLField(
                        blank=True, help_text="Link to the live project", null=True
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="Link to the source code", null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        validators=[
                            users.validators.validate_file_size,
                            users.validators.validate_image_extension,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="skills", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
