# Generated by Django 5.2.9 on 2025-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Tell the world about your stack.", null=True
            ),
        ),
    ]
