# Generated by Django 6.0.6 on 2026-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account will be permanently deleted",
                null=True,
            ),
        ),
    ]
