# Generated by Django 5.2.9 on 2025-12-11 17:50

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatar/",
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_image_extension,
                ],
            ),
        ),
    ]
