# Generated by Django 5.2.9 on 2025-12-15 08:24

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.rename_avatar,
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_image_extension,
                ],
            ),
        ),
    ]
