# Generated by Django 5.2.9 on 2025-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="Link to your github profile", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="Link to your linkedin profile", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="portfolio_url",
            field=models.URLField(
                blank=True, help_text="Your Portfolio website link", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stackoverflow_url",
            field=models.URLField(
                blank=True, help_text="Link to your StackOverflow profile", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                help_text="Link to your X (formerly twitter) profile",
                null=True,
            ),
        ),
    ]
