# Generated by Django 5.2.9 on 2025-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_github_url_customuser_linkedin_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fiver_url",
            field=models.URLField(
                blank=True, help_text="Your Fiver profile link", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="upwork_url",
            field=models.URLField(
                blank=True, help_text="Your Upwork profile link", null=True
            ),
        ),
    ]
