# Generated by Django 5.2.9 on 2026-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("dev", "Developer"),
                    ("client", "Client / Hirer"),
                    ("org", "Organization"),
                ],
                default="dev",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="e.g. Python, Django, React, AWS (Comma separated)",
                max_length=255,
            ),
        ),
    ]
