# Generated by Django 5.2.9 on 2026-01-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_role_customuser_tech_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="e.g. Python, Java, CI/CD, Unity... (Comma separated)",
                max_length=255,
            ),
        ),
    ]
