# Generated by Django 5.2.9 on 2026-01-15 15:15

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={
                    "min_length": "Username must be at least 4 characters long.",
                    "unique": "A user with that username already exists.",
                },
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    users.validators.validate_username,
                ],
            ),
        ),
    ]
