# Generated by Django 5.2.9 on 2026-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_experience_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Active Premium Subscription'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_boosts',
            field=models.IntegerField(default=0, help_text='Number of profile boosts purchased'),
        ),
    ]
