# /feed/urls.py

from django.urls import path
from .views import (
    ClientDashboardView,
    CommentDeleteView,
    CommentUpdateView,
    DeveloperDashboardView,
    HomePageView,
    AboutPageView,
    NotificationListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    ProposalActionView,
    ProposalCreateView,
    like_post,
    PostDetailView,
    search_results,
    InboxView,
    ChatThreadView,
    toggle_bookmark,
    submit_report,
    ModerationActionView,
    ModerationDashboardView,
    EcosystemDiscoveryView,
    HelpSupportView,
    SystemDocumentationView,
)


urlpatterns = [
    path(
        "",
        HomePageView.as_view(),
        name="home",
    ),
    path(
        "about/",
        AboutPageView.as_view(),
        name="about",
    ),
    path(
        "documentation/",
        SystemDocumentationView.as_view(),
        name="documentation",
    ),
    path(
        "post/new/",
        PostCreateView.as_view(),
        name="post_new",
    ),
    path(
        "post/<int:pk>/edit/",
        PostUpdateView.as_view(),
        name="post_edit",
    ),
    path(
        "post/<int:pk>/delete/",
        PostDeleteView.as_view(),
        name="post_delete",
    ),
    path(
        "post/<int:pk>/",
        PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "post/like/<int:pk>/",
        like_post,
        name="like_post",
    ),
    path(
        "comment/<int:pk>/edit/",
        CommentUpdateView.as_view(),
        name="comment_edit",
    ),
    path(
        "comment/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "search/",
        search_results,
        name="search",
    ),
    path(
        "notifications/",
        NotificationListView.as_view(),
        name="notifications",
    ),
    path(
        "explore/",
        EcosystemDiscoveryView.as_view(),
        name="jobs_clients",
    ),
    path(
        "support/",
        HelpSupportView.as_view(),
        name="support",
    ),
    path(
        "job/<int:pk>/apply/",
        ProposalCreateView.as_view(),
        name="apply_job",
    ),
    path(
        "proposal/<int:pk>/<str:action>/",
        ProposalActionView.as_view(),
        name="proposal_action",
    ),
    path(
        "dashboard/client/",
        ClientDashboardView.as_view(),
        name="client_dashboard",
    ),
    path(
        "dashboard/dev/",
        DeveloperDashboardView.as_view(),
        name="dev_dashboard",
    ),
    path(
        "inbox/",
        InboxView.as_view(),
        name="inbox",
    ),
    path(
        "inbox/<str:username>/",
        ChatThreadView.as_view(),
        name="chat_thread",
    ),
    path(
        "post/<int:pk>/bookmark/",
        toggle_bookmark,
        name="toggle_bookmark",
    ),
    path(
        "post/<int:pk>/report/",
        submit_report,
        name="submit_report",
    ),
    path(
        "moderation/",
        ModerationDashboardView.as_view(),
        name="moderation_dashboard",
    ),
    path(
        "moderation/<int:pk>/<str:action>/",
        ModerationActionView.as_view(),
        name="moderation_action",
    ),
]
