from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView
from users.models import CustomUser
from feed.models import Post
from .services import DevHuddleAIEngine
from .models import AIReport


class ProfileAnalyzerView(LoginRequiredMixin, View):
    def get(self, request, username):
        target_user = get_object_or_404(CustomUser, username=username)
        report = DevHuddleAIEngine.analyze_profile(target_user, request.user)

        return render(
            request,
            "intelligence/report.html",
            {"report": report, "target": target_user},
        )


class PostAnalyzerView(LoginRequiredMixin, View):
    def get(self, request, pk):
        target_post = get_object_or_404(Post, pk=pk)
        report = DevHuddleAIEngine.analyze_post(target_post, request.user)

        return render(
            request,
            "intelligence/report.html",
            {"report": report, "target": target_post},
        )


class AIDashboardView(LoginRequiredMixin, ListView):
    template_name = "intelligence/dashboard.html"
    context_object_name = "reports"

    def get_queryset(self):
        # Show all reports generated BY this user, or ABOUT this user
        return AIReport.objects.filter(requester=self.request.user).order_by(
            "-created_at"
        )
