# Generated by Django 6.0.6 on 2026-07-04 07:53

import feed.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=200)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            (
                                "welcome",
                                "Welcome! You can now update your profile in settings",
                            ),
                            ("premium", "Congrats on activating Premium profile!"),
                            (
                                "congrats",
                                "Congrats! You are ranking among the top members",
                            ),
                            (
                                "beware",
                                "Beware! Your are demoting from your higher ranking",
                            ),
                            (
                                "alert",
                                "Alert! System is under maintenance. Please be patient",
                            ),
                            ("like", "liked your post"),
                            ("comment", "commented on your post"),
                            ("reply", "replied to your comment"),
                            ("dm", "sent you a direct message (DM)"),
                            ("connect", "sent you a connection request"),
                            ("follow", "started following you"),
                            ("unfollow", "stopped following you"),
                            ("block", "has blocked you"),
                            ("boost", "boosted you"),
                            ("hire", "applied for the job"),
                            ("accept", "accepted your job proposal"),
                            ("reject", "declined your job proposal"),
                            ("visit", "visited your profile"),
                            ("profile", "checked your profile via AI Profile Analyzer"),
                            ("post", "is interested in your post"),
                            ("delete", "deleting your data was successful"),
                            (
                                "report_submitted",
                                "We received your report. Thank you for keeping DevHuddle safe!",
                            ),
                            (
                                "post_reported",
                                "One of your posts has been flagged by the community.",
                            ),
                        ],
                        max_length=26,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=feed.models.rename_post_image,
                        validators=[
                            users.validators.validate_file_size,
                            users.validators.validate_image_extension,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("huddle", "Huddle"),
                            ("job", "Job/Offer"),
                            ("ad", "Advertisement"),
                        ],
                        default="huddle",
                        max_length=10,
                    ),
                ),
                ("is_boosted", models.BooleanField(default=False)),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, help_text="For Ads/Jobs only", null=True
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        blank=True, help_text="Link for the Ad button", null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated tags (e.g. #python, #remote)",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        help_text="Why are you the best fit for this role?",
                        max_length=1500,
                    ),
                ),
                (
                    "bid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proposed budget in USD (Optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        default="Inappropriate Content or Spam", max_length=255
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
