# Generated by Django 5.2.9 on 2025-12-15 16:25

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_image_extension,
                ],
            ),
        ),
    ]
