# Generated by Django 5.2.9 on 2026-01-03 09:17

import feed.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=feed.models.rename_post_image,
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_image_extension,
                ],
            ),
        ),
    ]
