# Generated by Django 5.2.9 on 2026-01-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_boosted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("huddle", "Huddle"),
                    ("job", "Job/Offer"),
                    ("ad", "Advertisement"),
                ],
                default="huddle",
                max_length=10,
            ),
        ),
    ]
