# Generated by Django 5.2.9 on 2026-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome to DevHuddle_! Update your profile"),
                    ("like", "liked your post"),
                    ("comment", "commented on your post"),
                    ("follow", "started following you"),
                    ("block", "blocked you"),
                    ("boost", "boosted you"),
                    ("connect", "sent you a connection"),
                    ("dm", "sent you a message"),
                    ("hire", "wants to hire you"),
                    ("profile", "checked your profile"),
                    ("visit", "visited your profile"),
                ],
                max_length=26,
            ),
        ),
    ]
