# Generated by Django 5.2.9 on 2026-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_alter_notification_verb"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="For Ads/Jobs only", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma separated tags (e.g. #python, #remote)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="target_url",
            field=models.URLField(
                blank=True, help_text="Link for the Ad button", null=True
            ),
        ),
    ]
