# Generated by Django 5.2.9 on 2026-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0012_comment_parent_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    (
                        "welcome",
                        "Welcome to DevHuddle! You can update your profile in settings",
                    ),
                    ("like", "liked your post"),
                    ("comment", "commented on your post"),
                    ("reply", "replied to your comment"),
                    ("follow", "started following you"),
                    ("block", "has blocked you"),
                    ("boost", "boosted you"),
                    ("connect", "sent you a connection request"),
                    ("dm", "sent you a direct message (DM)"),
                    ("hire", "wants to hire you"),
                    ("profile", "checked your profile"),
                    ("visit", "visited your profile"),
                ],
                max_length=26,
            ),
        ),
    ]
