# Generated by Django 5.2.9 on 2026-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0013_alter_notification_verb"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
