# Generated by Django 5.2.9 on 2026-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0014_comment_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome! You can now update your profile in settings"),
                    (
                        "premium",
                        "Upgrade to Premium to unlock exclusive developer tools!",
                    ),
                    ("like", "liked your post"),
                    ("comment", "commented on your post"),
                    ("reply", "replied to your comment"),
                    ("follow", "started following you"),
                    ("block", "has blocked you"),
                    ("boost", "boosted you"),
                    ("connect", "sent you a connection request"),
                    ("dm", "sent you a direct message (DM)"),
                    ("hire", "wants to hire you"),
                    ("profile", "checked your profile"),
                    ("visit", "visited your profile"),
                ],
                max_length=26,
            ),
        ),
    ]
