# Generated by Django 5.2.9 on 2026-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0015_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome! You can now update your profile in settings"),
                    (
                        "premium",
                        "Upgrade to Premium for exclusive tools & opportunities!",
                    ),
                    ("congrats", "Congrats! You are ranking among the top members"),
                    ("beware", "Beware! Your are demoting from your higher ranking"),
                    ("alert", "Alert! System is under maintenance. Please be patient"),
                    ("like", "liked your post"),
                    ("comment", "commented on your post"),
                    ("reply", "replied to your comment"),
                    ("dm", "sent you a direct message (DM)"),
                    ("connect", "sent you a connection request"),
                    ("follow", "started following you"),
                    ("unfollow", "stopped following you"),
                    ("block", "has blocked you"),
                    ("boost", "boosted you"),
                    ("hire", "wants to hire you"),
                    ("visit", "visited your profile"),
                    ("profile", "checked your profile via AI Profile Checker"),
                    ("project", "interested in your projects"),
                    ("delete", "deleting your data was successful"),
                ],
                max_length=26,
            ),
        ),
    ]
