# Generated by Django 5.2.9 on 2026-05-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0016_alter_notification_verb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        help_text="Why are you the best fit for this role?",
                        max_length=1500,
                    ),
                ),
                (
                    "bid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proposed budget in USD (Optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        limit_choices_to={"post_type": "job"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="feed.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
